<?xml version="1.0"?><package format="3"><name>ambulance_msgs</name><version>0.1.0</version><description>Ambulance interfaces</description><maintainer email="research@example.org">Research Team</maintainer><license>Apache-2.0</license><buildtool_depend>rosidl_default_generators</buildtool_depend><depend>std_msgs</depend><member_of_group>rosidl_interface_packages</member_of_group></package>
